name: Build

on:
  push:
    branches:
      - main


jobs:
  build:
    name: Build
    runs-on: self-hosted
    permissions: read-all
    steps:
      - name: Build and analyze
        env:
         shell: powershell
        run: |
          C:\Users\"Sergio Vega"\.dotnet\tools\dotnet-sonarscanner begin /k:"vegasergio2851_eSHopOnWeb_AYuXZ111lV_fnToDXzUy" /d:sonar.token="sqp_e962901425529466c37ce3a0a0411a9acfd87e02" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          dotnet build
          C:\Users\"Sergio Vega"\.dotnet\tools\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
